name: bactpipe
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc
  - trimmomatic
  - spades
  - quast
  - prodigal
  - barrnap
  - trnascan-se
  - abricate
  - mlst
  - minced
