cd /data/sayed/bactpipe_pipeline/BactPipe

cat > environment.yml << 'EOF'
name: bactpipe
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc
  - trimmomatic
  - spades
  - quast
  - prodigal
  - barrnap
  - trnascan-se
  - abricate
  - mlst
  - minced
EOF
